export default class CashfreeConstants {

    public static readonly EVENTS = {
        TRANSFER_SUCCESS: 'TRANSFER_SUCCESS',
        TRANSFER_FAILED: 'TRANSFER_FAILED',
        TRANSFER_REVERSED: 'TRANSFER_REVERSED',
        TRANSFER_ACKNOWLEDGED: 'TRANSFER_ACKNOWLEDGED',
        INVALID_BENEFICIARY_ACCOUNT: 'INVALID_BENEFICIARY_ACCOUNT',
    };
}
