export interface IDish {
    readonly id: number;
    buddyId: number;
    name: string;
    description: string;
    dishType: string;
    dishContent: string;
    servings: number;
    remainingServings: number;
    orderEndTime: string;
    preparationEndTime: string;
    cost: number;
    serviceCharge: number;
    netCost: number;
    deliveryCharge: number;
    autoConfirm: number;
    addressOption: string;
    addressId: number;
    categoryId: number;
    isEnable: number;
    isDeleted: number;
    hidden: number;
    tagId: number;
    thumbId: number;
    dishSchedularId: number;
    rating: number;
    level: string;
    points: number;
    currentWeekPoints: number;
    lastWeekPoints: number;
    isAccountUpdated: number;
    postType: string;
    bookmarks: number;
    isPriceEditable: number;
    cronPointsUpdatedAt: string;
    lastWeekBookmarks: number;
    lastWeekRatings: number;
    isVisibileToSeller: number;
    isSignatureDish: number;
    priceUpdatedAt: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

export default IDish;
